sudo: false
language: node_js
node_js:
  - 4
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - "npm run test:api:unit"
  - "npm run test:api:integration"
  - "npm run test:client:unit"
  - "npm run test:client:integration"