sudo: false
language: node_js
node_js:
  - 6
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - "npm run test"
after_success: 'NODE_ENV=production npm run build && gulp zip'
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "dist/budget-shary-$(git tag --points-at HEAD).zip"
  skip_cleanup: false
  on:
    tags: true