sudo: false
language: node_js
node_js:
  - 6
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - "npm run test"
  - "npm run lint"
after_success:
  - "rm -rf ./dist/js"
  - "NODE_ENV=production"
  - "npm run build"
  - "gulp zip"
  - "npm run deploy"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "dist/budget-shary-$(git tag --points-at HEAD).zip"
  skip_cleanup: true
  on:
    tags: true