sudo: false
language: node_js
node_js:
  - 6
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - "npm run test"
  after_success: 'npm run build'
  deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: "dist/js/bundle.build.js"
    skip_cleanup: true
    on:
      tags: true